repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: uv run --frozen ruff check
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff format
        entry: uv run --frozen ruff format --check
        language: system
        types: [python]
      - id: mypy
        name: Mypy
        entry: uv run --frozen mypy src
        language: system
        pass_filenames: false
        types: [python]
